server:
  port: 8080

spring:
  application:
    name: kitt-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

# Firebase Configuration
firebase:
  service-account-key: ${FIREBASE_SERVICE_ACCOUNT_KEY:pulse-bengaluru-backend-firebase-adminsdk-fbsvc-1155be068e.json}
  database-url: ${FIREBASE_DATABASE_URL:https://pulse-bengaluru-backend-default-rtdb.firebaseio.com}

# External API Configuration
external:
  api:
    base-url: https://api.example.com
    data-endpoint: /api/v1/data
    job1-endpoint: /api/v1/job1/data
    job2-endpoint: /api/v1/job2/data
    job3-endpoint: /api/v1/job3/data
    timeout: 30000

# Cron Configuration
cron:
  job1:
    schedule: "0 */2 * * * *"  # Every 2 minutes
  job2:
    schedule: "0 */2 * * * *"  # Every 2 minutes
  job3:
    schedule: "0 */2 * * * *"  # Every 2 minutes

logging:
  level:
    com.example.kitt: DEBUG
    org.springframework.security: DEBUG